# Set to false to disable entire plugin
pluginEnabled: true

# Worlds to disable this plugin in, good for Creative, Battle Arenas and worlds where scoreboard conflicts
disabledWorlds: 
    - example1
    - creative

# Disabled commandswhen player is tagged in combat
disabledCommands: 
    - home
    - spawn
    - heal
    - warp
    - tpa

# Disable teleporting when player is tagged in combat
disableTeleport: true

# Set true to remove invisibility from players who are tagged in combat
removeInvisible: false 


Tagging:
    NameTag Color: 'c'        #Color that the nametag of unsafe people will be

    Disable Enderpearls: true #Disables enderpearls for people who are unsafe
    Anti Pilejump: true       #Only the people who were PVPing in the unsafe zone can continue to pvp
    Disable Flying: true      #Stops flight for those who aren't safe
    Safe Time: 20
    Use TagAPI: true          #Set to false to use scoreboard instead
Death:
    DeathTP Enabled: false
    DeathTP Time: 20         #Amount of seconds before players can teleport after death
PvPLogger Zombie:
    Enabled: true
    Keep Player Health: true #Set true to make the zombie spawn with the player's health
    Health: 20
    Allow Regen: true        #Set true to allow zombie to regen health over what player had when they logged (up to Health defined above)
Scoreboard Display:
    Safe Time: true
