pluginEnabled: true

# Worlds to disable this plugin in, good for Creative, Battle Arenas and worlds where scoreboard conflicts
disabledWorlds: 
    - example1
    - creative

# Disabled commands when player is tagged in combat
disabledCommands: 
    - home
    - spawn
    - heal
    - warp
    - tpa

# Disable teleporting when player is tagged in combat, this conflicts with plugins like worldborder, better to use disabledCommands
disableTeleport: false

# Set true to remove invisibility from players who are tagged in combat, default to false because it breaks default game mechanic
removeInvisible: false 

# Color of the nametag of players in combat
tagColor: 'c'

# Disables enderpearls for  players in combat, default to false because it breaks default game mechanic
disableEnderpearls: false

# Block players who are not tagged to attack tagged players in safe zones
antiPilejump: false

# Block flying from players who are tagged in combat
disableFlying: true     

# How long in seconds, will a tag last
tagTime: 20

# Use the scoreboard to display time left til the tag wears off
displayTagTime: true

# Use TagAPI, if set false plugin will fallback to scoreboard - wont work after 1.8
enableTagAPI: false

# Enable death TP timer
deathTPEnabled: true

# Time in seconds, a player is not allowed to teleport after dying
deathTPTime: 20  
       
# Enable replacing players who log out of combat with a mob
mobEnabled: true

# mob will spawn with the player's health
keepPlayerHealth: true
 
# max health available (20 is a normal players default) 
maxHealth: 20

# Set true to allow the mob to regen health over what player had when they logged (up to Health defined above)    
allowRegen: true  